# Generated by Django 5.1.3 on 2024-12-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DollarSign', '0008_stock_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='purchase_price',
        ),
        migrations.AddField(
            model_name='stock',
            name='latestPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='marketCap',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='peRatio',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='previousClose',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='returnYTD',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='shares',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='week52High',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='week52Low',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
